default:
	@/opt/toolchains/gcc-linaro-arm-linux-gnueabihf-4.9-2014.09_linux/bin/arm-linux-gnueabihf-gcc -c bfdd.c -lrt -lpthread  
	@/opt/toolchains/gcc-linaro-arm-linux-gnueabihf-4.9-2014.09_linux/bin/arm-linux-gnueabihf-ar crv libbfdd.a bfdd.o	
clean:
	@rm -rf bfdd.o libbfdd.a	
